import type { Lang } from '@/types'

type Row = [string, string, string, string, string, string, string]
const codes: Lang[] = ['ko', 'en', 'ja', 'zh', 'fr', 'es', 'de']

const rows: Row[] = [
  ['전체','All','すべて','全部','Tout','Todo','Alle'], ['목록으로','Back to list','一覧へ','返回列表','Retour à la liste','Volver a la lista','Zur Liste'],
  ['다시 불러오기','Reload','再読み込み','重新加载','Recharger','Recargar','Neu laden'], ['검색 조건에 맞는 장소가 없습니다.','No places match your search.','検索条件に合う場所がありません。','没有符合条件的地点。','Aucun lieu ne correspond.','No hay lugares coincidentes.','Keine passenden Orte.'],
  ['서울 지역 정보','Seoul area guide','ソウル地域情報','首尔地区信息','Guide de Séoul','Guía de Seúl','Seoul-Guide'], ['나에게 맞는 서울 찾기','Find your Seoul','自分に合うソウルを探す','寻找适合你的首尔','Trouvez votre Séoul','Encuentra tu Seúl','Finde dein Seoul'],
  ['관광지·혼밥·카페·자연 정보를 검색하고 카드를 눌러 상세 정보와 하단 지도를 확인하세요.','Search attractions, solo dining, cafés, and nature, then open a card for details and a map.','観光地・ひとりごはん・カフェ・自然を検索し、カードから詳細と地図を確認できます。','搜索景点、单人用餐、咖啡馆和自然景点，点击卡片查看详情和地图。','Recherchez attractions, repas solo, cafés et nature, puis ouvrez une carte pour les détails.','Busca atracciones, lugares para comer solo, cafés y naturaleza; abre una tarjeta para ver detalles.','Suche Sehenswürdigkeiten, Solo-Restaurants, Cafés und Natur und öffne eine Karte für Details.'],
  ['장소명, 지역, 태그 검색','Search places, areas, or tags','場所・地域・タグを検索','搜索地点、地区或标签','Rechercher lieux, quartiers ou tags','Buscar lugares, zonas o etiquetas','Orte, Bezirke oder Tags suchen'],
  ['관광지','Attractions','観光地','景点','Sites','Atracciones','Sehenswürdigkeiten'], ['레포츠','Leisure sports','レポーツ','休闲运动','Sports de loisirs','Deportes recreativos','Freizeitsport'], ['문화시설','Cultural facilities','文化施設','文化设施','Équipements culturels','Instalaciones culturales','Kultureinrichtungen'], ['쇼핑','Shopping','ショッピング','购物','Shopping','Compras','Shopping'], ['숙박','Accommodation','宿泊','住宿','Hébergement','Alojamiento','Unterkünfte'], ['여행코스','Travel courses','旅行コース','旅行路线','Circuits','Rutas de viaje','Reiserouten'], ['축제공연행사','Festivals & events','祭り・公演・イベント','节庆演出活动','Festivals et événements','Festivales y eventos','Festivals & Veranstaltungen'],
  ['서울의 관광지·레포츠·문화시설·쇼핑·숙박·여행코스·축제공연행사를 유형별로 탐색하고 상세 정보를 확인하세요.','Explore Seoul attractions, leisure sports, cultural facilities, shopping, accommodation, travel courses, festivals, and events by type.','ソウルの観光地・レポーツ・文化施設・ショッピング・宿泊・旅行コース・祭りやイベントを種類別に探索できます。','按类型探索首尔的景点、休闲运动、文化设施、购物、住宿、旅行路线和节庆活动。','Explorez par type les sites, sports, lieux culturels, boutiques, hébergements, circuits et festivals de Séoul.','Explora por tipo atracciones, deportes, cultura, compras, alojamiento, rutas y festivales de Seúl.','Entdecke Seouls Sehenswürdigkeiten, Freizeitsport, Kultur, Shopping, Unterkünfte, Routen und Festivals nach Typ.'],
  ['쇼핑·전시','Shopping & exhibitions','ショッピング・展示','购物与展览','Shopping et expositions','Compras y exposiciones','Shopping & Ausstellungen'],
  ['장소 소개','About this place','場所紹介','地点介绍','Présentation','Acerca del lugar','Über diesen Ort'], ['이용 정보','Visitor information','利用情報','使用信息','Informations pratiques','Información de visita','Besucherinformationen'],
  ['주소','Address','住所','地址','Adresse','Dirección','Adresse'], ['혼행 추천 점수','Solo travel score','ひとり旅おすすめスコア','独行推荐评分','Score voyage solo','Puntuación para viajar solo','Solo-Reise-Wertung'], ['카테고리','Category','カテゴリー','类别','Catégorie','Categoría','Kategorie'],
  ['혼행 추천','Solo travel pick','ひとり旅おすすめ','独行推荐','Conseil solo','Recomendación solo','Solo-Empfehlung'], ['공유하기','Share','共有','分享','Partager','Compartir','Teilen'], ['북마크','Bookmark','ブックマーク','收藏','Favori','Guardar','Merken'], ['저장됨','Saved','保存済み','已保存','Enregistré','Guardado','Gespeichert'],
  ['데이터 정보','Data information','データ情報','数据信息','Informations des données','Información de datos','Dateninformationen'], ['콘텐츠 ID','Content ID','コンテンツID','内容ID','ID du contenu','ID de contenido','Inhalts-ID'], ['콘텐츠 유형','Content type','コンテンツタイプ','内容类型','Type de contenu','Tipo de contenido','Inhaltstyp'],
  ['서울 축제 캘린더','Seoul festival calendar','ソウル祭りカレンダー','首尔节庆日历','Calendrier des festivals','Calendario de festivales','Seouler Festivalkalender'], ['혼자도, 함께도 즐거운 축제','Festivals to enjoy alone or together','ひとりでも一緒でも楽しい祭り','独自或结伴都精彩的节庆','Des festivals seul ou à plusieurs','Festivales solo o en compañía','Festivals allein oder gemeinsam'],
  ['동행 모집하기','Find a companion','同行者を募集','寻找同伴','Trouver un compagnon','Buscar acompañante','Begleitung finden'], ['축제가 있는 날','Festival days','祭りのある日','有节庆的日期','Jours de festival','Días con festivales','Festivaltage'], ['오늘','Today','今日','今天',"Aujourd'hui",'Hoy','Heute'],
  ['선택한 날짜','Selected date','選択した日','所选日期','Date sélectionnée','Fecha seleccionada','Gewähltes Datum'], ['자세히 보기 →','View details →','詳細を見る →','查看详情 →','Voir les détails →','Ver detalles →','Details →'], ['축제 목록','Festival list','祭り一覧','节庆列表','Liste des festivals','Lista de festivales','Festivalliste'],
  ['축제 소개','About the festival','祭り紹介','节庆介绍','Présentation du festival','Acerca del festival','Über das Festival'], ['방문 정보','Visitor information','訪問情報','访问信息','Informations pratiques','Información de visita','Besucherinformationen'], ['기간','Dates','期間','日期','Dates','Fechas','Zeitraum'], ['장소','Place','場所','地点','Lieu','Lugar','Ort'], ['지역','Area','地域','地区','Quartier','Zona','Bezirk'], ['전화번호','Phone','電話番号','电话号码','Téléphone','Teléfono','Telefon'],
  ['익명 혼행 커뮤니티','Anonymous solo travel community','匿名ひとり旅コミュニティ','匿名独行社区','Communauté solo anonyme','Comunidad anónima','Anonyme Solo-Community'], ['새 글 작성','New post','新規投稿','发布新帖','Nouvelle publication','Nueva publicación','Neuer Beitrag'], ['제목·내용·태그 검색','Search title, content, or tags','タイトル・内容・タグを検索','搜索标题、内容或标签','Rechercher titre, contenu ou tags','Buscar título, contenido o etiquetas','Titel, Inhalt oder Tags suchen'],
  ['게시글을 불러오는 중입니다…','Loading post…','投稿を読み込み中…','正在加载帖子…','Chargement…','Cargando publicación…','Beitrag wird geladen…'], ['커뮤니티 목록','Community list','コミュニティ一覧','社区列表','Liste de la communauté','Lista de la comunidad','Community-Liste'], ['좋아요','Like','いいね','点赞',"J'aime",'Me gusta','Gefällt mir'], ['수정','Edit','編集','编辑','Modifier','Editar','Bearbeiten'], ['삭제','Delete','削除','删除','Supprimer','Eliminar','Löschen'], ['취소','Cancel','キャンセル','取消','Annuler','Cancelar','Abbrechen'],
  ['익명 게시글 작성','Create anonymous post','匿名投稿を作成','发布匿名帖子','Créer une publication anonyme','Crear publicación anónima','Anonymen Beitrag erstellen'], ['게시글 수정','Edit post','投稿を編集','编辑帖子','Modifier la publication','Editar publicación','Beitrag bearbeiten'], ['게시글 유형','Post type','投稿タイプ','帖子类型','Type de publication','Tipo de publicación','Beitragstyp'], ['닉네임','Nickname','ニックネーム','昵称','Pseudo','Apodo','Nickname'], ['비밀번호','Password','パスワード','密码','Mot de passe','Contraseña','Passwort'], ['제목','Title','タイトル','标题','Titre','Título','Titel'], ['내용','Content','内容','内容','Contenu','Contenido','Inhalt'], ['태그','Tags','タグ','标签','Tags','Etiquetas','Tags'], ['게시글 등록','Publish post','投稿する','发布帖子','Publier','Publicar','Veröffentlichen'],
  ['익명 닉네임','Anonymous nickname','匿名ニックネーム','匿名昵称','Pseudo anonyme','Apodo anónimo','Anonymer Nickname'], ['4자 이상','At least 4 characters','4文字以上','至少4个字符','Au moins 4 caractères','Al menos 4 caracteres','Mindestens 4 Zeichen'], ['제목을 입력하세요','Enter a title','タイトルを入力','请输入标题','Saisissez un titre','Introduce un título','Titel eingeben'], ['혼밥, 경복궁, 동행 (쉼표로 구분)','Solo dining, Gyeongbokgung, companion (comma-separated)','ひとりごはん、景福宮、同行（カンマ区切り）','单人用餐、景福宫、同伴（逗号分隔）','Repas solo, Gyeongbokgung, compagnon (séparés par des virgules)','Comer solo, Gyeongbokgung, acompañante (separado por comas)','Solo-Essen, Gyeongbokgung, Begleitung (kommagetrennt)'],
  ['오늘의 AI 인사이트',"Today's AI insights",'今日のAIインサイト','今日AI洞察',"Analyses IA du jour",'Ideas de IA de hoy','Heutige KI-Einblicke'], ['분석 중...','Analyzing…','分析中…','分析中…','Analyse…','Analizando…','Analyse…'], ['새로고침','Refresh','更新','刷新','Actualiser','Actualizar','Aktualisieren'], ['다시 시도','Try again','再試行','重试','Réessayer','Reintentar','Erneut versuchen'],
  ['지금 많이 찾는 키워드','Popular searches now','今人気のキーワード','当前热门搜索','Recherches populaires','Búsquedas populares','Beliebte Suchbegriffe'], ['서울 탐색','Explore Seoul','ソウル探索','探索首尔','Explorer Séoul','Explorar Seúl','Seoul entdecken'], ['전체 보기 →','View all →','すべて見る →','查看全部 →','Tout voir →','Ver todo →','Alle anzeigen →'], ['글쓰기','Write','投稿','发帖','Écrire','Escribir','Schreiben'],
  ['이미지 없음','No image','画像なし','无图片',"Pas d'image",'Sin imagen','Kein Bild'], ['일정 정보 없음','No schedule','日程情報なし','无日程信息','Aucune date','Sin horario','Kein Termin'], ['위치 지도','Location map','位置地図','位置地图','Carte','Mapa de ubicación','Lagekarte'], ['큰 지도 열기','Open large map','大きな地図を開く','打开大地图','Ouvrir la carte','Abrir mapa grande','Große Karte öffnen'],
]

const dictionaries = Object.fromEntries(codes.map((code, index) => [
  code,
  Object.fromEntries(rows.map((row) => [row[0], row[index]])),
])) as Record<Lang, Record<string, string>>

export function translateStatic(text: string, lang: Lang) {
  const exact = dictionaries[lang][text]
  if (exact || lang === 'ko') return exact ?? text
  let match = text.match(/^(\d+)월$/)
  if (match) return lang === 'ja' ? `${match[1]}月` : lang === 'zh' ? `${match[1]}月` : `${match[1]} ${lang === 'de' ? 'Monat' : lang === 'fr' ? 'mois' : lang === 'es' ? 'mes' : 'month'}`
  match = text.match(/^총 (\d+)개$/)
  if (match) return lang === 'ja' ? `全${match[1]}件` : lang === 'zh' ? `共${match[1]}个` : lang === 'fr' ? `${match[1]} au total` : lang === 'es' ? `${match[1]} en total` : lang === 'de' ? `${match[1]} insgesamt` : `${match[1]} total`
  match = text.match(/^(\d+)개의 축제$/)
  if (match) return lang === 'ja' ? `${match[1]}件の祭り` : lang === 'zh' ? `${match[1]}个节庆` : lang === 'fr' ? `${match[1]} festivals` : lang === 'es' ? `${match[1]} festivales` : lang === 'de' ? `${match[1]} Festivals` : `${match[1]} festivals`
  return text
}
